# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greenTechGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(797, 634)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(238, 255, 248);\n"
"color: rgb(0, 0, 0);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.labelGreenGrocery = QtGui.QLabel(self.centralwidget)
        self.labelGreenGrocery.setGeometry(QtCore.QRect(180, 30, 461, 31))
        self.labelGreenGrocery.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.labelGreenGrocery.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGreenGrocery.setObjectName(_fromUtf8("labelGreenGrocery"))
        self.labelGreenTech = QtGui.QLabel(self.centralwidget)
        self.labelGreenTech.setGeometry(QtCore.QRect(280, 0, 241, 31))
        self.labelGreenTech.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);"))
        self.labelGreenTech.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGreenTech.setObjectName(_fromUtf8("labelGreenTech"))
        self.labelAcct = QtGui.QLabel(self.centralwidget)
        self.labelAcct.setGeometry(QtCore.QRect(10, 80, 71, 31))
        self.labelAcct.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAcct.setObjectName(_fromUtf8("labelAcct"))
        self.labelDate = QtGui.QLabel(self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(490, 80, 81, 31))
        self.labelDate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(550, 80, 91, 22))
        self.dateEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 2, 26), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.labelTime = QtGui.QLabel(self.centralwidget)
        self.labelTime.setGeometry(QtCore.QRect(640, 80, 81, 31))
        self.labelTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTime.setObjectName(_fromUtf8("labelTime"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(700, 80, 91, 22))
        self.timeEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.timeEdit.setTime(QtCore.QTime(14, 24, 44))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 80, 131, 21))
        self.comboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.lineOnTop = QtGui.QFrame(self.centralwidget)
        self.lineOnTop.setGeometry(QtCore.QRect(0, 60, 801, 20))
        self.lineOnTop.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnTop.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnTop.setObjectName(_fromUtf8("lineOnTop"))
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 150, 791, 231))
        self.tableView.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.labelSearch = QtGui.QLabel(self.centralwidget)
        self.labelSearch.setGeometry(QtCore.QRect(10, 390, 231, 16))
        self.labelSearch.setStyleSheet(_fromUtf8("font: 75 9pt \"MS Shell Dlg 2\";"))
        self.labelSearch.setObjectName(_fromUtf8("labelSearch"))
        self.lineOnTop2 = QtGui.QFrame(self.centralwidget)
        self.lineOnTop2.setGeometry(QtCore.QRect(0, 110, 801, 20))
        self.lineOnTop2.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnTop2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnTop2.setObjectName(_fromUtf8("lineOnTop2"))
        self.labelSubTotal = QtGui.QLabel(self.centralwidget)
        self.labelSubTotal.setGeometry(QtCore.QRect(580, 390, 71, 21))
        self.labelSubTotal.setObjectName(_fromUtf8("labelSubTotal"))
        self.lineEditSubTotal = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSubTotal.setGeometry(QtCore.QRect(650, 380, 141, 31))
        self.lineEditSubTotal.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditSubTotal.setObjectName(_fromUtf8("lineEditSubTotal"))
        self.lineEditSearch = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSearch.setGeometry(QtCore.QRect(10, 410, 381, 20))
        self.lineEditSearch.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditSearch.setText(_fromUtf8(""))
        self.lineEditSearch.setPlaceholderText(_fromUtf8(""))
        self.lineEditSearch.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
        self.bnSearch = QtGui.QPushButton(self.centralwidget)
        self.bnSearch.setGeometry(QtCore.QRect(390, 410, 71, 23))
        self.bnSearch.setObjectName(_fromUtf8("bnSearch"))
        self.bnAdd = QtGui.QPushButton(self.centralwidget)
        self.bnAdd.setGeometry(QtCore.QRect(470, 410, 41, 23))
        self.bnAdd.setObjectName(_fromUtf8("bnAdd"))
        self.labelTax = QtGui.QLabel(self.centralwidget)
        self.labelTax.setGeometry(QtCore.QRect(580, 410, 71, 31))
        self.labelTax.setObjectName(_fromUtf8("labelTax"))
        self.labelDiscount = QtGui.QLabel(self.centralwidget)
        self.labelDiscount.setGeometry(QtCore.QRect(580, 440, 71, 31))
        self.labelDiscount.setObjectName(_fromUtf8("labelDiscount"))
        self.labelReceived = QtGui.QLabel(self.centralwidget)
        self.labelReceived.setGeometry(QtCore.QRect(580, 500, 71, 31))
        self.labelReceived.setObjectName(_fromUtf8("labelReceived"))
        self.labelTotal = QtGui.QLabel(self.centralwidget)
        self.labelTotal.setGeometry(QtCore.QRect(580, 470, 71, 31))
        self.labelTotal.setObjectName(_fromUtf8("labelTotal"))
        self.lineEditTax = QtGui.QLineEdit(self.centralwidget)
        self.lineEditTax.setGeometry(QtCore.QRect(650, 420, 113, 20))
        self.lineEditTax.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTax.setObjectName(_fromUtf8("lineEditTax"))
        self.lineEditDiscount = QtGui.QLineEdit(self.centralwidget)
        self.lineEditDiscount.setGeometry(QtCore.QRect(650, 450, 113, 20))
        self.lineEditDiscount.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditDiscount.setObjectName(_fromUtf8("lineEditDiscount"))
        self.lineEditTotal = QtGui.QLineEdit(self.centralwidget)
        self.lineEditTotal.setGeometry(QtCore.QRect(650, 480, 113, 20))
        self.lineEditTotal.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTotal.setObjectName(_fromUtf8("lineEditTotal"))
        self.labelBalance = QtGui.QLabel(self.centralwidget)
        self.labelBalance.setGeometry(QtCore.QRect(580, 530, 71, 31))
        self.labelBalance.setObjectName(_fromUtf8("labelBalance"))
        self.lineEditReceived = QtGui.QLineEdit(self.centralwidget)
        self.lineEditReceived.setGeometry(QtCore.QRect(650, 510, 113, 20))
        self.lineEditReceived.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditReceived.setObjectName(_fromUtf8("lineEditReceived"))
        self.lineEditBalance = QtGui.QLineEdit(self.centralwidget)
        self.lineEditBalance.setGeometry(QtCore.QRect(650, 540, 113, 20))
        self.lineEditBalance.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditBalance.setObjectName(_fromUtf8("lineEditBalance"))
        self.bnSubmit = QtGui.QPushButton(self.centralwidget)
        self.bnSubmit.setGeometry(QtCore.QRect(440, 490, 75, 23))
        self.bnSubmit.setObjectName(_fromUtf8("bnSubmit"))
        self.bnUpdate = QtGui.QPushButton(self.centralwidget)
        self.bnUpdate.setGeometry(QtCore.QRect(30, 480, 75, 23))
        self.bnUpdate.setObjectName(_fromUtf8("bnUpdate"))
        self.bnRefresh = QtGui.QPushButton(self.centralwidget)
        self.bnRefresh.setGeometry(QtCore.QRect(130, 510, 75, 23))
        self.bnRefresh.setObjectName(_fromUtf8("bnRefresh"))
        self.bnS = QtGui.QPushButton(self.centralwidget)
        self.bnS.setGeometry(QtCore.QRect(230, 510, 75, 23))
        self.bnS.setObjectName(_fromUtf8("bnS"))
        self.bnSave = QtGui.QPushButton(self.centralwidget)
        self.bnSave.setGeometry(QtCore.QRect(340, 510, 75, 23))
        self.bnSave.setObjectName(_fromUtf8("bnSave"))
        self.bnCancel = QtGui.QPushButton(self.centralwidget)
        self.bnCancel.setGeometry(QtCore.QRect(340, 460, 75, 23))
        self.bnCancel.setObjectName(_fromUtf8("bnCancel"))
        self.bnNew = QtGui.QPushButton(self.centralwidget)
        self.bnNew.setGeometry(QtCore.QRect(230, 460, 75, 23))
        self.bnNew.setObjectName(_fromUtf8("bnNew"))
        self.bnDelete = QtGui.QPushButton(self.centralwidget)
        self.bnDelete.setGeometry(QtCore.QRect(130, 460, 75, 23))
        self.bnDelete.setObjectName(_fromUtf8("bnDelete"))
        self.lineOnBottom = QtGui.QFrame(self.centralwidget)
        self.lineOnBottom.setGeometry(QtCore.QRect(0, 560, 791, 16))
        self.lineOnBottom.setFrameShape(QtGui.QFrame.HLine)
        self.lineOnBottom.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineOnBottom.setObjectName(_fromUtf8("lineOnBottom"))
        self.labelDesigned = QtGui.QLabel(self.centralwidget)
        self.labelDesigned.setGeometry(QtCore.QRect(240, 570, 301, 31))
        self.labelDesigned.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);\n"
"color: rgb(255, 0, 0);\n"
"font: 8pt \"Lucida Handwriting\";"))
        self.labelDesigned.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDesigned.setObjectName(_fromUtf8("labelDesigned"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GREEN-TECH", None))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.labelGreenGrocery.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">GREEN GROCERY POINT OF SALE SYSTEM</span></p></body></html>", None))
        self.labelGreenTech.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">GREEN-TECH</span></p></body></html>", None))
        self.labelAcct.setText(_translate("MainWindow", "ACCT", None))
        self.labelDate.setText(_translate("MainWindow", "DATE", None))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy", None))
        self.labelTime.setText(_translate("MainWindow", "TIME", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Cash", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Credit Card", None))
        self.labelSearch.setText(_translate("MainWindow", "Enter the Product to Search Below:-", None))
        self.labelSubTotal.setText(_translate("MainWindow", "Sub-Total", None))
        self.bnSearch.setText(_translate("MainWindow", "SEARCH", None))
        self.bnAdd.setText(_translate("MainWindow", "ADD", None))
        self.labelTax.setText(_translate("MainWindow", "Tax", None))
        self.labelDiscount.setText(_translate("MainWindow", "Discount", None))
        self.labelReceived.setText(_translate("MainWindow", "Received", None))
        self.labelTotal.setText(_translate("MainWindow", "TOTAL", None))
        self.labelBalance.setText(_translate("MainWindow", "BALANCE", None))
        self.bnSubmit.setText(_translate("MainWindow", "SUBMIT", None))
        self.bnUpdate.setText(_translate("MainWindow", "UPDATE", None))
        self.bnRefresh.setText(_translate("MainWindow", "REFRESH", None))
        self.bnS.setText(_translate("MainWindow", "SUBMIT", None))
        self.bnSave.setText(_translate("MainWindow", "SAVE", None))
        self.bnCancel.setText(_translate("MainWindow", "CANCEL", None))
        self.bnNew.setText(_translate("MainWindow", "NEW", None))
        self.bnDelete.setText(_translate("MainWindow", "DELETE", None))
        self.labelDesigned.setText(_translate("MainWindow", "Designed By: K. A. Muriungi & P.K. Ndung\'u", None))

